learning_users/basicApp/urls.py
from django.urls import path
from basicApp import views

#template variables
app_name='basicApp'

urlpatterns=[
        path('register/',views.register,name='register'),
        path('userlogin/',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basicApp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicApp/',include('basicApp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

learning_users/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)
#additional classes
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_users/basicApp/views.py
from django.shortcuts import render
from basicApp.forms import UserForm,UserProfileInfoForm
# Create your views here.

#may be an error, i think
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout



def index(request):
    return render(request,'basicApp/index.html')

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
                profile.save()
                registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basicApp/registration.html',
                        {'user_form':user_form,
                        'profle_form':profile_form,
                        'registered':registered})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print('Someone tried to login and failed!')
            print('Username: {} anf password: {}'.format(username,password))
            return HttpResponse("Invalid Login Details")
    else:
        return render(request,'basicApp/login.html',{ })

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponseResponse('You are logged in !! NICE')

learning_users/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>
  <body>
        <nav class="navbar navbar-expand-sm bg-dark">
          <div class="container">
            <ul class="navbar-nav">
              <li class="nav-item"><a class="navbar-brand" href="{%url 'index'%}">DJANGO</a> </li>
              <li class="nav-item"><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
              <li class="nav-item"><a class="navbar-link" href="{%url 'basicApp:register'%}">Register</a></li>
              {%if user.is_authenticated%}
              <li><a class="navbar-link" href="{%url 'logout'%}">Logout</a></li>
              {%else%}
              <li><a class="navbar-link" href="{%url 'basicApp:user_login'%}">Login</a></li>
              {%endif%}
            </ul>
          </div>
        </nav>

        <div class="container">
          {%block body_block%}
          {%endblock%}
        </div>
  </body>
</html>

learning_users/templates/basicApp/index.html
{%extends "basicApp/base.html"%}
{%block body_block%}

<div class="jumbotron">
    <h1>DJANGO</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
       Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
       in reprehenderit in voluptate velit esse cillum dolore eu fugiat
        nulla pariatur. Excepteur sint occaecat cupidatat non proident,
        sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{%endblock%}

learning_users/templates/basicApp/login.html
{%extends 'basicApp/base.html'%}
{%block body_block%}

<div class="jumbotron">
  <h1>Please log in</h1>
  <form  action="{%url 'basicApp:user_login'%}" method="POST">
    {%csrf_token%}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
</div>

{%endblock%}

learning_users/templates/basicApp/registration.html
{%extends "basicApp/base.html"%}
{%load static%}

{%block body_block%}
<div class="jumbotron">
  {%if registered%}
    <h1>Thank you for registering!!</h1>
  {%else%}
    <h1>Register Here!!</h1>
    <h3>Fill out the form:</h3>
    <form  enctype="multipart/form-data" method="POST">
      {%csrf_token%}
      {{user_form.as_p}}
      {{profle_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>
    {%endif%}
</div>

{%endblock%}